//Tests go here; this will not be compiled when this package is used as a libraryR
Robot.Predkosc(50)
Robot.DoPrzodu(1000)
let n1 = Robot.Odleglosc()
Robot.ZmienPredkosc(0, 0)
Robot.ZmienPredkosc(0, 0)
Robot.LEDOnLewy()
Robot.LEDOnPrawy()
Robot.LEDOffLewy()
Robot.LEDOffPrawy()
Robot.MrugajLED(20)
Robot.MrugajRGB(20)
